# Generated by Django 4.1 on 2025-09-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "pb",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "ms",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "ed",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Classificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nutriente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("unidade", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "classificacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alimentos.classificacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComposicaoAlimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=9, default=0.0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "alimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alimentos.alimento",
                    ),
                ),
                (
                    "nutriente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alimentos.nutriente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alimento",
            name="classificacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="alimentos.classificacao",
            ),
        ),
    ]
