# Generated by Django 4.1 on 2025-10-06 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        default="fotos_perfil/default.jpg",
                        null=True,
                        upload_to="fotos_perfil/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png", "jpeg"]
                            )
                        ],
                    ),
                ),
                ("proprietario", models.CharField(max_length=100)),
                ("peso_vivo", models.DecimalField(decimal_places=2, max_digits=6)),
                ("data_nasc", models.DateField()),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Macho"), ("F", "Fêmea")], max_length=1
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("id_dieta", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
