# Generated by Django 4.1 on 2025-10-06 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animais", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="imagem",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to="fotos_perfil/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
    ]
