# Generated by Django 4.1 on 2025-10-20 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dietas", "0001_initial"),
        ("animais", "0002_alter_animal_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="id_dieta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dietas.dieta",
            ),
        ),
    ]
