# Generated by Django 4.1 on 2025-11-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_alter_animal_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='id_dieta',
        ),
    ]
