# Generated by Django 4.1 on 2025-10-20 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exigencias", "0001_initial"),
        ("alimentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dieta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.CharField(max_length=250)),
                ("especifica", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exigencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exigencias.exigencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComposicaoDieta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=9, default=0.0, max_digits=15),
                ),
                (
                    "alimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alimentos.alimento",
                    ),
                ),
                (
                    "dieta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dietas.dieta"
                    ),
                ),
            ],
        ),
    ]
