# Generated by Django 4.1 on 2025-11-10 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0005_remove_animal_id_dieta'),
        ('dietas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dieta',
            old_name='especifica',
            new_name='atual',
        ),
        migrations.AddField(
            model_name='dieta',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.animal'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
