# Generated by Django 4.1 on 2025-11-10 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dietas", "0002_rename_especifica_dieta_atual_dieta_animal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dieta",
            name="data_criacao",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
