# Generated by Django 4.1 on 2025-11-10 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0003_alter_dieta_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
