# Generated by Django 4.1 on 2026-01-10 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exigencias", "0001_initial"),
        ("alimentos", "0001_initial"),
        ("dietas", "0004_alter_dieta_data_criacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaTemporaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "alimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alimentos.alimento",
                    ),
                ),
                (
                    "exigencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exigencias.exigencia",
                    ),
                ),
            ],
            options={
                "unique_together": {("exigencia", "alimento")},
            },
        ),
    ]
