# Generated by Django 4.1 on 2026-01-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dietas", "0005_dietatemporaria"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DietaTemporaria",
        ),
    ]
