# Generated by Django 4.1 on 2025-09-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alimentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fase", models.IntegerField(default=0)),
                ("esforco", models.CharField(default="Sem esforço", max_length=255)),
                (
                    "peso_vivo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "gmd",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Exigencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "pb",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "ed",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exigencias.categoriaanimal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComposicaoExigencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exigencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exigencias.exigencia",
                    ),
                ),
                (
                    "nutriente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alimentos.nutriente",
                    ),
                ),
            ],
        ),
    ]
